[project]
name = "mcp_client"
version = "0.1.0"
description = "Demo MCP client for weather questions"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "lxml>=6.0.0",
    "mcp>=1.12.2",
    "openai>=1.97.1",
]

[tool.uv]
