[project]
name = "mcp_server"
version = "0.1.0"
description = "Demo MCP server for weather questions"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "mcp>=1.12.2",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
]

[tool.uv]
